# Generated by Django 6.0.7 on 2026-07-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsystem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentsystem',
            name='email',
        ),
    ]
