"""
a=10
b=20
print(a==b)
print(a!=b)
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)
"""
a=10
b=10
equal=a==b
notequal=a!=b
greaterthan=a>b
lessthan=a<b
greaterthanorequal=a>=b
lessthanorequal=a<=b
print(f"equal={equal}")
print(f"notequal={notequal}")
print(f"greaterthan={greaterthan}")
print(f"lessthan={lessthan}")
print(f"greaterthanorequal={greaterthanorequal}")
print(f"lessthanorequal={lessthanorequal}")