# Generated by Django 6.1 on 2026-08-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
