# Generated by Django 6.1 on 2026-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.TextField(blank=True),
        ),
    ]
