# Generated by Django 6.1 on 2026-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_profile_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
    ]
