# Generated by Django 6.1 on 2026-08-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_profile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
