# Generated by Django 6.1 on 2026-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_profile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
