# Generated by Django 6.1 on 2026-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_applications_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(default='2026-08-28'),
            preserve_default=False,
        ),
    ]
