# Generated by Django 6.0.7 on 2026-07-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date',
            field=models.DateField(auto_now_add=True, default='2026-07-22'),
            preserve_default=False,
        ),
    ]
