# Generated by Django 6.0.7 on 2026-08-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='charactor_name',
            new_name='character_name',
        ),
    ]
