# Generated by Django 6.0.7 on 2026-08-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_charactor_name_cast_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='character_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
