# Generated by Django 6.0.7 on 2026-07-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('movies', '0002_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director'), ('PRODUCER', 'Producer')], max_length=20)),
                ('charactor_name', models.CharField(max_length=40)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.actors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
        ),
    ]
