# Generated by Django 6.0.7 on 2026-08-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_cast_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.category'),
        ),
    ]
