# Generated by Django 6.0.7 on 2026-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('picture', models.ImageField(upload_to='actors')),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Actors',
                'verbose_name_plural': 'Actors',
            },
        ),
    ]
