# Generated by Django 6.0.7 on 2026-08-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='dob',
        ),
    ]
